export const dummyPosts = [
  {
    _id: "1",
    title: "Mastering React Basics",
    subtitle: "Understanding components, props, and state",  
    content: "React is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI components React is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI componentsReact is a popular JavaScript library for building user interfaces. It allows developers to build reusable UI components...",
    image: "https://imgs.search.brave.com/Er7su-yJ3g32LnLeAh6ajncHJ3fxX8wf_adQTLm3RNc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9kM25q/amNiaGJvamJvdC5j/bG91ZGZyb250Lm5l/dC9hcGkvdXRpbGl0/aWVzL3YxL2ltYWdl/cHJveHkvaHR0cHM6/Ly9jb3Vyc2VyYS1j/b3Vyc2UtcGhvdG9z/LnMzLmFtYXpvbmF3/cy5jb20vNjUvNGNk/NzllYzcwOTQ0NmU5/MjhkODM5ZTg4NGQw/MDM3L1JlYWN0LUZ1/bmRhbWVudGFscy5w/bmc_YXV0bz1mb3Jt/YXQsJTIwY29tcHJl/c3MsJTIwZW5oYW5j/ZSZkcHI9MSZ3PTMy/MCZoPTE4MCZmaXQ9/Y3JvcCZxPTUw",
    author: "Sanjai",
    authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
    date: "2025-08-01",
  },
  {
    _id: "2",
    title: "Getting Started with Node.js",
    subtitle: "A beginner's guide to backend JavaScript",
    content: "Node.js is a runtime environment that lets you run JavaScript on the server. It uses an event-driven, non-blocking I/O model...",
    image: "https://imgs.search.brave.com/TTKt2NFj2mK6WmSkz-8CmtWrEy87KbnrRffnmC3poyE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZGlnaXRhbG9jZWFu/LmNvbS9hcGkvc3Rh/dGljLWNvbnRlbnQv/djEvaW1hZ2VzP3Ny/Yz1odHRwczovL2Nv/bW11bml0eS1jZG4t/ZGlnaXRhbG9jZWFu/LWNvbS5nbG9iYWwu/c3NsLmZhc3RseS5u/ZXQvb1FRVGhiWXZM/enRkb1ZKN3lXWmNz/NzdzJndpZHRoPTE5/MjA",
    author: "Sanjai",
    authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
    date: "2025-08-02",
  },
  {
    _id: "3",
    title: "Exploring MongoDB",
    subtitle: "NoSQL database for modern apps",
    content: "MongoDB stores data in flexible, JSON-like documents, meaning fields can vary from document to document...",
    image: "https://imgs.search.brave.com/P49R8u2psN6yUnm3LhdjspzpRUbnJ3GZEmKpSZrPhdE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/c2h1dHRlcnN0b2Nr/LmNvbS9pbWFnZS1w/aG90by9tb25nb2Ri/LXNpZ24tbG9nby1v/bi1zaWxpY29uLTI2/MG53LTE0Mjg5ODIz/MDQuanBn",
    author: "Sanjai",
    authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
    date: "2025-08-03",
  },
  {
    _id: "4",
    title: "Frontend vs Backend Development",
    subtitle: "Understanding the two sides of web development",
    content: "Frontend refers to the client side, while backend refers to the server side of a web application...",
    image: "https://imgs.search.brave.com/6eDlArh5mqWxwr9JJ8WTWVFB9Befqmm7U3HxJuy8D-o/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzA1LzAzLzg5LzUx/LzM2MF9GXzUwMzg5/NTE5NF96RjJmYXp1/RWpwaXJTSVZXSExO/cTVBcWhyYzNvTHI5/RC5qcGc",
    author: "Sanjai",
    authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
    date: "2025-08-04",
  },
  {
    _id: "5",
    title: "Top 5 VS Code Extensions",
    subtitle: "Boost your productivity with these tools",
    content: "Visual Studio Code supports extensions for linting, formatting, and many other developer needs...",
    image: "https://imgs.search.brave.com/9bwF4MRNEUV5wgSOG1v-kRmgDpoif71sMw6kZuKhEMg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMxLnhkYWltYWdl/cy5jb20vd29yZHBy/ZXNzL3dwLWNvbnRl/bnQvdXBsb2Fkcy93/bS8yMDI1LzA1L3Zz/LWNvZGUtcHJldHRp/ZXIuanBn",
    author: "Sanjai",
    date: "2025-08-05",
    authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
  },
  {
    _id: "6",
    title: "CSS Grid vs Flexbox",
    subtitle: "Which layout system should you use?",
    content: "Grid and Flexbox are powerful layout systems in CSS. Grid is best for 2D layouts, while Flexbox excels in 1D...",
    image: "https://imgs.search.brave.com/7kK-1FG3BFBkZE2i2Es4FzveshKFdCgF-NPR1lCqjPM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jeW5v/dGVjay5jb20vd3At/Y29udGVudC91cGxv/YWRzLzIwMjEvMTIv/Y3NzLWdyaWQtdnMt/ZmxleGJveC5qcGc",
    author: "Sanjai",
    authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
    date: "2025-08-06",
  },
  {
    _id: "7",
    title: "JavaScript ES6 Features",
    subtitle: "Let, const, arrow functions, and more",
    content: "ES6 brought many new features to JavaScript, such as let and const for variable declarations, arrow functions, and template literals...",
    image: "https://imgs.search.brave.com/1de8_SJF-x56eiojcdeeyEZdwUSi_J7T5vbqwsaR_Gk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oYWNr/ZXJub29uLmltZ2l4/Lm5ldC9obi1pbWFn/ZXMvMSpiNGQ1Qmh5/aVVxX3VFZ19HNDBW/bXZ3LnBuZz9hdXRv/PWZvcm1hdCZmaXQ9/bWF4Jnc9MjA0OA",
    author: "Sanjai",
    authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
    date: "2025-08-07",
  },
  {
    _id: "8",
    title: "Building Responsive Websites",
    subtitle: "Making your site mobile-friendly",
    content: "Responsive design means your site looks good on all screen sizes. Use media queries, fluid grids, and flexible images...Responsive design means your site looks good on all screen sizes. Use media queries, fluid grids, and flexible images...Responsive design means your site looks good on all screen sizes. Use media queries, fluid grids, and flexible images...Responsive design means your site looks good on all screen sizes. Use media queries, fluid grids, and flexible images...Responsive design means your site looks good on all screen sizes. Use media queries, fluid grids, and flexible images...Responsive design means your site looks good on all screen sizes. Use media queries, fluid grids, and flexible images...",
    image: "https://imgs.search.brave.com/fVilsGq4B_OFqtHXaGMw72pEGZVcZcdMMOEeWO6Xzoc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMudG9wdGFsLmlv/L2ltYWdlcz91cmw9/aHR0cHM6Ly9icy11/cGxvYWRzLnRvcHRh/bC5pby9ibGFja2Zp/c2gtdXBsb2Fkcy9j/b21wb25lbnRzL2Js/b2dfcG9zdF9wYWdl/LzQwODY5NzQvY292/ZXJfaW1hZ2UvcmVn/dWxhcl8xNzA4eDY4/My9SZXNwb25zaXZl/X0Rlc2lnbi0xMjAw/eDYyOC01ODcxN2Nl/NzE4ODczMzJiY2Uz/ZGQ1NzQyZTcwYjI0/Ny5wbmc",
    authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
    author: "Sanjai",
    date: "2025-08-08",
  },
  {
    _id: "9",
    title: "Git & GitHub Basics",
    subtitle: "Version control for developers",
    content: "Git helps track changes in your code. GitHub is a cloud platform where you can host and share your repositories...",
    image: "https://imgs.search.brave.com/Jyi5-ZeN-qeS88FBXsQzSWzUoqQSWVKMMxGujaIU0tw/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/c2ltcGxpbGVhcm4u/Y29tL2ljZTkvZnJl/ZV9yZXNvdXJjZXNf/YXJ0aWNsZV90aHVt/Yi93aGF0X2lzX2dp/dGh1Yi5qcGc",
    authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
    author: "Sanjai",
    date: "2025-08-09",
  },
  {
    _id: "10",
    title: "Deploying with Netlify",
    subtitle: "Host your site in minutes",
    content: "Netlify is a powerful platform to deploy static websites. Just connect your GitHub repo and it handles the rest...",
    // authorAvatar:"https://imgs.search.brave.com/fTmdpOyFLQOo6p7WsZpXDyN__eqBnnXRLz84SDvanuY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/dmVjdG9yc3RvY2su/Y29tL2kvNTAwcC82/Mi81OS9zaW1wbGUt/Z3JheS1wbGFjZWhv/bGRlci1hdmF0YXIt/dmVjdG9yLTIxNjY2/MjU5LmpwZw",
    image: "https://imgs.search.brave.com/WF58DxfUwCjcIIi3M_D2YdvZjKyYr9zT0AcvYjcM7bU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuYXBpZG9nLmNv/bS9ibG9nLW5leHQv/MjAyNS8wNy9pbWFn/ZS0yNzMucG5n",
    author: "Sanjai",
    date: "2025-08-10",
  },
];


export const topics = ["Web Development", "JavaScript", "React", "AI & ML", "Tech News", "Tools & Tips"];


export const userData={
    name: "Sanjai",
    bio: "Full Stack Developer | MERN",
    image: "https://imgs.search.brave.com/RIJ78YvOZhv5816VrwB5tzHiPRFlP8twQoBuoPsjRmk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTQ1/MTU4NzgwNy92ZWN0/b3IvdXNlci1wcm9m/aWxlLWljb24tdmVj/dG9yLWF2YXRhci1v/ci1wZXJzb24taWNv/bi1wcm9maWxlLXBp/Y3R1cmUtcG9ydHJh/aXQtc3ltYm9sLXZl/Y3Rvci5qcGc_cz02/MTJ4NjEyJnc9MCZr/PTIwJmM9eURKNElU/WDFjSE1oMjVMdDF2/STF6Qm4yY0FLS0Fs/QnlIQnZQSjhnRWlJ/Zz0"
}